version: "3.9"

services:
  strapi:
    container_name: volunteer-strapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production

      # PostgreSQL connection
      DATABASE_CLIENT: postgres
      DATABASE_HOST: 103.82.38.96
      DATABASE_PORT: 5441
      DATABASE_NAME: volunteer-cms-strapi-db
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_SSL: "false"

      # App keys and secrets
      APP_KEYS: myKeyA,myKeyB,myKeyC,myKeyD
      API_TOKEN_SALT: 9hG82xFgPslj39hFGH83
      ADMIN_JWT_SECRET: 6f2cbbaf3e7e47a583a204b3c94b07f8
      TRANSFER_TOKEN_SALT: 3jfsd8f3jsdlf83j==

    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge